version: "3.7"
services:
  web:
    image: fedora:latest
    container_name: web
    command: >
      /bin/bash -c "
      dnf -y install python3 && 
      python3 -m http.server --bind 0.0.0.0 8080"
    ports:
      - "8080:8080"